kind: pipeline
type: docker
name: STAGE1

steps:
- name: en
  image: alpine
  commands:
  - echo hello world

- name: fr
  image: alpine
  commands:
  - echo bonjour monde
  when:
   branch:
   - master
