kind: pipeline
type: docker
name: ALPINE

steps:
- name: en
  image: alpine 
  commands:
  - echo "Creating a greet file"
  - touch greet && echo GM >> greet
  - cat greet && pwd && uname -a
  - node -v
  
---

kind: pipeline
type: docker
name: NODEjs

steps:
- name: en
  image: node 
  commands:
  - echo "Creating a greet file"
  - touch greet && echo GA >> greet
  - cat greet && pwd && uname -a
  - node -v
